### PR TITLE
completed paintings#controller

### PR DESCRIPTION
**Pull request by Samanthha**
Hey girls, can one of you check that my paintings#controller makes sense? :)
Also, I would need help with the delete method.

### CODE REVIEW

**Comment by Samanthha** [comment]
Fixed, thank you :)

**Comment by Samanthha** [comment]
Dont we need to fix the delete method before committing to master?

**Comment by So1ene** [comment]
You’re right, I committed so I could pull from master and work on it

**Comment by Samanthha** [comment]
ah ok got it

**Pull request merged**
